server.port=8089

# email
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=342252328@qq.com
spring.mail.password=yhttmfxcbhqkbheg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# vmrack stock monitor email alert
vmrack.stock-monitor.email-enabled=true
vmrack.stock-monitor.email-to=342252328@qq.com
vmrack.stock-monitor.test-alert-on-start=false
